[package]
name = "ResearchTokenization"
version = "0.0.1"
authors = ["Shawn Chee"]
edition = "2024.beta"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
research_fund = "0x0"
research = "0x0"
mockusdt = "0x0"

# The Iota framework automatically adds these standard addresses
# std = "0x1" 
# iota = "0x2"